scripts:
  - /epicomp/assets/js/epicomp.js
stylesheets:
  - /epicomp/assets/css/epicomp.css
author: Tactical Command
description: Entries through the years for Tactical Command's EpiComp, a 6mm sci-fi miniature painting competition.
tagline: The 6mm sci-fi painting competition.
title: EpiComp

# Where things are
source: _site
destination: public_html
sass:
  sass_dir: _scss
  style: compressed
  load_paths:
    - node_modules
javascript:
  load_paths:
    - node_modules

# Serving
baseurl: /epicomp
# undocumented, but this is prepended with the absolute_url filter when the site is built (but not served)
url: https://tacticalwargames.net

# Outputting
timezone: America/New_York

# Outputting
defaults:
  -
    values:
      layout: default
