scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.20/lodash.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js
  - /epicomp/assets/js/epicomp.js
stylesheets:
  - https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css
  - /epicomp/assets/css/epicomp.css
author: Tactical Command
description: Entries through the years for Tactical Command's EpiComp, a 6mm sci-fi miniature painting competition.
tagline: The 6mm sci-fi painting competition.
title: EpiComp

# Where things are
source: ./_site
destination: ./public_html

# Serving
baseurl: /epicomp
# undocumented, but this is prepended with the absolute_url filter when the site is built (but not served)
url: https://tacticalwargames.net

# Outputting
timezone: America/New_York

# Outputting
defaults:
  -
    values:
      layout: default
